### ISSUE TITLE
No longer working in Magento 2.3.3

### ISSUE THREAD

**Issue by MNOiSY** [nadeem0035/allow-html-tags#1]
After upgrading to 2.3.3, this is no longer allowing HTML tags in the footer copyright. Reinstallation does not resolve issues.

**Comment by nadeem0035** [comment]
Module updated and now its compatible with magneto 2.3.3.
I have Checked with fresh magento 2.3.3 and also upgrade from 2.3.2 to 2.3.3 and its working now.
